version: '2'

services:
  postgres:
    image: postgres:alpine
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  website:
    depends_on:
      - 'postgres'
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
    volumes:
      - '.:/usr/src/app'
    volumes_from:
    - box

  box:
    image: busybox
    volumes:
      - /box

volumes:
  postgres:
  box: